# Heredity

## 17: The RNA World and Genetic Information {-}

+ Introduce the structure of RNA and its properties, including its ability to catalyze reactions
+ Ribosomes are largely made of RNA, and ribonucleotide moieties in many coenzymes, such as acetyl-CoA, NADH, FADH, and F420, may be surviving remnants of covalently bound coenzymes in an RNA world
+ Explain how genes code for phenotypes
+ Explain why genetic information is necessary for evolution to occur
+ RNA not super-great for complex life information storage, touch on that
+ If the RNA world existed, it was probably followed by an age characterized by the evolution of ribonucleoproteins (RNP world), which in turn ushered in the era of DNA and longer proteins
+ Introduce the structure of DNA

## 18: DNA Replication {-}

+ Strand complementarity and semi-conservative replication
+ DNA polymerase and replication machinery
+ Initiation, elongation, termination (leading/lagging strand, replication fork, and necessary enzymes)
+ Regulation and proofreading

## 19: Transcription {-}

+ DNA is stored in the nucleus as chromatin
+ Chromatin unraveled and mRNA is made
+ RNA polymerases
+ Initiation, elongation, termination
+ mRNA processesing


## 20: Translation {-}

+ mRNA travels to cytoplasm and meets ribosome
+ Start codon and initiation
+ Elongation, ribosome sites, tRNA
+ termination
+ protein processing

## 21: Why RNA first? {-}

+ Summarize evidence for RNA first world
+ But, how the heck do we assemble polynucleotides without enzymes?
+ But how do we get proteins without information storage?
+ In truth, there were hundreds of millions of years for chemicals to interact in aqueous environments, meaning that life was probably built slowly in many different stages throughout this time
+ Once we have information storage, energy capture, and compartmentalization, we need to be able to reproduce
+ Evolution occurs when progeny have different genotypes than their progenitors--"descent w modification"
+ Individuals that have traits that allow them to survive and reproduce do, and those that can't die---introduce biological fitness