# Policies {-}

## Course grading {-}

Your grade will be based on the following components: attendance, participation, and the completion of your assignments. This means that doing well in this class depends on **showing up**, **being prepared**, and **putting effort** into assigned activities. **To receive a "Satisfactory" grade, you will need to demonstrate proficiency in two of the three areas outlined below.**

On week 9, you will receive a progress report from me indicating your achievement in each of these three areas and feedback for improvement. You are also welcome to schedule a meeting with me at any time to discuss your progress in the course. For a running total of your grade, visit [My Grades in Blackboard](https://uic.blackboard.com/ultra/courses/_207074_1/cl/outline): there is one entry for each week, where you will earn one point for attending, one point for participating, and one point for turning in your assignment on time the following week.

### Rubric {-}

```{r}
library(tidyverse)
col1 <- enframe(c("Proficient", 
                  "Developing",
                  "Emerging"), name = NULL, value = "Levels")

col2 <- enframe(c("No more than two missed classes", 
                  "No more than four missed classes",
                  "Missed more than four classes"), 
                name = NULL, value = "Attendance")
 
col3 <- enframe(c("Regular substantive and meaningful participation in class, indicating you have done the reading and are listening to your classmates", 
                  "Occasional substantive and meaningful participation in class, indicating you have done the reading and are listening to your classmates", 
                  "Little substantive participation in class"), name = NULL, value = "Participation")

col4 <- enframe(c("No more than one missed assignment", 
                  "No more than two missed assignments",
                  "More than two missed assignments"), 
                name = NULL, value = "Assignments")

table <- cbind(col1, col2, col4, col3) 
names(table) <- c("", "Attendance", "Assignments", "Participation")

knitr::kable(
  table, booktabs = TRUE,
) %>%
  kableExtra::kable_styling(bootstrap_options = 
                              c("striped", "hover", "condensed", "responsive")) %>%
   kableExtra::column_spec(1, bold = T, border_right = T, width = "5em") %>%
   kableExtra::column_spec(2, width = "9em") %>%
   kableExtra::column_spec(3, width = "9em") %>%
   kableExtra::column_spec(4, width = "13em")

```

## Code of conduct {-}

1. **Be excellent to each other**. Our class is a community. It is vital that everyone feels welcome and that we all work together to create a safe space. We will be wrestling with some complex topics -- some personal -- and we will _all_ get the most out of this exercise if we create an environment where folks of every disposition feel comfortable sharing their experiences. This means listening to each other non-judgmentally and validating the experiences of others. 
2. **Be considerate of each other**. We are all human beings -- we all have good days, bad days, feelings, and frustrations. Let's make sure all of our interactions in class start with this understanding. Honor the experiences and thoughts of others: we never know what someone else is going through, so let's always assume best intentions. This means we assume our classmates do not intend to hurt us with their words.
3. **Be respectful of each other**. Disagreement is natural. We are all different, and we should celebrate our differences and learn from one another! But we can only do this if we maintain respect for our classmates at all times. This means we always use kind words and inclusive language, and we never attack the character or experience of another person.

## Instructor responsibilities {-}

As your instructor, I will also abide by the outlined code of conduct above. In addition, I will:

1. Foster an inclusive environment for every student.
2. Return assignments and enter grades within one week of their due date.
3. Respond to student emails within 24-hours.
4. Maintain an open-door policy and make myself available for student questions, concerns, or feedback via email, drop-in hours, or individual meetings.
5. Acknowledge that I will make mistakes, listen thoughtfully and respectfully to students that bring these mistakes to my attention, and change my behavior accordingly.

## Celebrating diversity {-}

UIC is one of the most diverse public research universities in the US. At UIC, diversity is not an end in itself, but a vehicle for advancing access, equity, and inclusion. Every student in this class will be honored and respected as an individual with distinct experiences, talents, and backgrounds. Students will be treated fairly regardless of race, religion, sexual orientation, gender identification, disability, socio-economic status, or national identity. 

When you fill out your welcome survey, please indicate your pronouns, your name if it differs from official records, and any other information you feel is important for me to know. Within the classroom, we will always abide by the code of conduct as outlined above. If you have any concerns or suggestions for improving the classroom climate, please do not hesitate to speak with me.

## Absences and late work {-}

In general, communicate with me as soon as you are aware you may miss class or miss an assignment. Since a good portion of your grade is based on attendance and participation, it is important to make every effort to show up to class. That said, you are free to miss two classes and one assignment for any reason with no impact to your grade. Beyond that, I will work with individual students on a case-by-case basis as circumstances arise. Speak with me so that we can create a plan.

## Mental health resources {-}

As an institution, UIC is invested in the mental health and well-being of all of our students, faculty, and staff. We believe that promoting the well-being of our students is a necessary and integral part of learning. If you are experiencing challenges related to your mental health or overall well-being, please utilize campus resources and reach out to faculty, mentors, advisors, peers, and counselors whom you trust. If you would like formal counseling services, the UIC Counseling Services is located in room 2010 of SSB (Student Services Building) and the phone number is 312-996-3490. Please do not hesitate to reach out to me if you are struggling in any way.

## Accessibility resources {-}

It is of the utmost importance to me that you feel safe and valued, and that your academic, mental, physical, and emotional needs are met. Should you need specific accommodations, please reach out to me and we will work together to ensure the proper supports are put in place. If you have a letter of accommodation from a doctor, therapist, or the UIC Office of Disability, please give me a copy during the first week of class so I can incorporate any accommodations or modifications. 

UIC is committed to maintaining a barrier-free environment so that all students with disabilities can fully access programs, courses, services, and activities at UIC. Students with disabilities who require accommodations for access to and/or participation in this course must register with the Disability Resource Center (DRC). You may contact DRC at 312-413-2183 (phone) or 773-649-4535 (VP/relay) and consult the [DRC Guide to Accommodations](https://drc.uic.edu/guide-to-accommodations/).